<?php

use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Generates a permission string for a given a role name.
 */
function _administerusersbyrole_build_perm_string($role_id, $op = 'edit') {
  $perm = "$op users with role $role_id";
  return $perm;
}

/**
 * Implements hook_help().
 */
function administerusersbyrole_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.administerusersbyrole':
      $output = '<h3>About</h3>';
      $output .= "<p>Administer Users by Role llows site builders to set up fine-grained permissions for
          allowing \"sub-admin\" users to edit and delete other users ? more specific
          than Drupal Core's all-or-nothing 'administer users' permission. It also
          provides and enforces a 'create users' permission. <br />";

      $output .= "Manage users, role and permissions in <a href=\"!pa_url\">People Administration page</a></p>";
      $output .= "<br><h3>New permissions</h3>";
      $output .= "<h6>Create new users</h6>";
      $output .= "Create users, at admin/people/create. If in the account settings (/admin/config/people/accounts) the administrator select that Visitors can register accounts but administrator approval is required, the accounts created will be as blocked account. If the administrator select that Visitors can create accounts, the accounts created will be as active";

      $output .= "<h6>Edit users with no custom roles</h6>";
      $output .= "Allows editing of any authenticated user that has no custom roles set.";
      $output .= "<h6>Edit users with no custom roles</h6>";
      $output .= "Allows editing of any authenticated user with the specified role.
        To edit a user with multiple roles, the sub-admin must have permission to
        edit ALL of those roles.  (\"Edit users with no custom roles\" is NOT needed.)";

      $output .= "<h6>Edit users with {role} role</h6>";

      $output .= "Allows edit accounts that have a custom role that the administrator creates <br />";

      $output .= "<br><strong>The permission for cancel work exactly the same as those for edit.</strong>";

      return t($output, array('!pa_url' => Url::fromRoute('user.admin_account')));
      break;
  }
}
